services:
    payum.tcompayway.action.capture_payment:
        class: Locastic\TcomPaywayPayumBundle\Action\CaptureAction
        tags:
            - { name: payum.action, factory: tcompayway }

    locastic_tcom_pay_way.form.card:
        class: Locastic\TcomPaywayPayumBundle\Form\Type\CreditCardType
        tags:
           - { name: form.type, alias: locastic_credit_card }
