locastic_tcompaywaypayum_prepare:
    pattern: /prepare
    defaults:
        _controller: LocasticTcomPaywayPayumBundle:Payment:prepare

locastic_tcompaywaypayum_capture_done:
    pattern: /done
    defaults:
        _controller: LocasticTcomPaywayPayumBundle:Payment:captureDone